### ISSUE TITLE
Update dependencies and fix tests

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/RoutingAutoBundle#161]
The tests are currently failing because:

- The minimum requirement for the Routing dependency is too low (or we are doing something wrong). The Route object needs to implement the `setParentObject` @dbu 
- We are using the pre-1.3 annotations and need to upgrade the new `@Field(type="<xxx>")` syntax for the PHP7 tests to pass, and make the minimum version of the ODM 1.3.

**Comment by WouterJ** [comment]
Tests do now pass again in master (see https://github.com/symfony-cmf/RoutingAutoBundle/pull/162). PHP 7 support should still be in the allowed failures (due to a typo, it wasn't in there).

I think this can be closed, updating to 1.3 (for PHP 7 support) is something we have to do for almost all bundles. It might be a good idea to do this now.
